COMMANDE GM EMULATEUR NOSAFTER !

toute les commands:
$lang <pack> (change ta langue du server)
$infos (information du server)
-Gm commands:
$gold <gold> (nombre de l"or que tu veux)
$mgold <nom> <or> (update nom or)
$speed <speed> (1-59)
$kick <nom> (kick la personnr)
$upSp <up> <aile> (change your sp upgrade)
$eq <1,2,3> <rarity> <upgrade> (up you eq)
$mute <user> (mute the user)
$ban <user> (ban the user)
$port <map> <x> <y> (teleport on map)
$summon <user> (teleport the user)
$follow <user> (teleport to the user)
$scale <scale>
$announce <message> (Send the message to all user, on all channels).
$gps + nombre del user(ver posición del jugador).
